Fix electoral office request test
After switching to use a model the test was failing with:

ActionView::Template::Error:
       undefined method `introduction' for an instance of ContentItem
     # ./app/models/content_item.rb:45:in `method_missing'
     # ./app/views/local_transaction/index.html.erb:13:in `block in _app_views_local_transaction_index_html_erb___2070635762823176923_40080'
     # ./app/views/shared/_base_page.html.erb:19:in `_app_views_shared__base_page_html_erb__3913279142670048899_40120'
     # ./app/views/local_transaction/index.html.erb:7:in `_app_views_local_transaction_index_html_erb___2070635762823176923_40080'
     # ./app/controllers/electoral_controller.rb:19:in `show'
     # ./spec/requests/contact_electoral_registration_office_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `introduction' for an instance of ContentItem
     #   ./app/models/content_item.rb:45:in `method_missing'